/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#041329",
        foreground: "#d6e3ff",
        primary: "#adc7ff",
        "surface-container-lowest": "#010e24",
        "primary-fixed-dim": "#adc7ff",
        "secondary-fixed-dim": "#4cd6ff",
        "secondary": "#a6e6ff",
        "on-error": "#690005",
        "on-secondary-container": "#00566b",
        "outline": "#8b90a0",
        "secondary-fixed": "#b7eaff",
        "primary-container": "#4a8eff",
        "surface-dim": "#041329",
        "error-container": "#93000a",
        "inverse-surface": "#d6e3ff",
        "surface": "#041329",
        "on-error-container": "#ffdad6",
        "surface-bright": "#2c3951",
        "on-tertiary-fixed": "#351000",
        "surface-tint": "#adc7ff",
        "surface-variant": "#27354c",
        "on-secondary": "#003543",
        "tertiary-container": "#ef6719",
        "secondary-container": "#14d1ff",
        "surface-container-low": "#0d1c32",
        "on-primary-container": "#00285b",
        "on-primary": "#002e68",
        "surface-container-highest": "#27354c",
        "on-tertiary-fixed-variant": "#7c2e00",
        "on-surface": "#d6e3ff",
        "tertiary-fixed": "#ffdbcc",
        "surface-container-high": "#1c2a41",
        "primary-fixed": "#d8e2ff",
        "on-primary-fixed-variant": "#004493",
        "on-secondary-fixed": "#001f28",
        "outline-variant": "#414754",
        "tertiary": "#ffb695",
        "surface-container": "#112036",
        "on-background": "#d6e3ff",
        "on-surface-variant": "#c1c6d7",
        "on-tertiary-container": "#4c1a00",
        "on-tertiary": "#571e00",
        "error": "#ffb4ab",
        "inverse-primary": "#005bc0",
        "on-secondary-fixed-variant": "#004e60",
        "inverse-on-surface": "#233148",
        "tertiary-fixed-dim": "#ffb695",
        "on-primary-fixed": "#001a41",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "0.5rem",
        md: "calc(0.5rem - 2px)",
        sm: "calc(0.5rem - 4px)",
        xl: "0.75rem",
        full: "9999px"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries")
  ],
}
