/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1280px",
      },
    },
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#3323cc",
        "secondary-fixed-dim": "#c2c6d3",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#404758",
        "surface-variant": "#dce2f3",
        "on-secondary": "#ffffff",
        "tertiary": "#414859",
        "on-secondary-container": "#60646f",
        "surface-dim": "#d3daea",
        "on-surface-variant": "#464555",
        "secondary-fixed": "#dee2ef",
        "surface-container-low": "#f0f3ff",
        "outline": "#777587",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#ebf1ff",
        "on-primary": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "secondary-container": "#dee2ef",
        "secondary": "#5a5e69",
        "surface-container-high": "#e2e8f8",
        "on-secondary-fixed": "#171c25",
        "surface-tint": "#4d44e3",
        "primary-fixed-dim": "#c3c0ff",
        "tertiary-container": "#596072",
        "background": "#f9f9ff",
        "on-tertiary-fixed": "#141b2b",
        "primary-fixed": "#e2dfff",
        "tertiary-fixed-dim": "#c0c6db",
        "on-tertiary-container": "#d5dbf0",
        "primary-container": "#4f46e5",
        "primary": "#3525cd",
        "surface-container-highest": "#dce2f3",
        "on-primary-fixed": "#0f0069",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#424751",
        "on-primary-container": "#dad7ff",
        "surface": "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "on-surface": "#151c27",
        "on-error": "#ffffff",
        "outline-variant": "#c7c4d8",
        "surface-container": "#e7eefe",
        "tertiary-fixed": "#dce2f7",
        "inverse-surface": "#2a313d",
        "on-background": "#151c27",
        border: "#E5E7EB",
        input: "#E5E7EB",
        ring: "#4F46E5",
        foreground: "#111827",
        success: "#10B981",
        warning: "#F59E0B",
        "section-bg": "#F8FAFC",
        "card-bg": "#FFFFFF",
        "code-bg": "#F3F4F6",
        "text-primary": "#111827",
        "text-secondary": "#6B7280",
        "text-muted": "#9CA3AF",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "#F3F4F6",
          foreground: "#9CA3AF",
        },
        accent: {
          DEFAULT: "#EEF2FF",
          foreground: "#4F46E5",
        },
        popover: {
          DEFAULT: "#FFFFFF",
          foreground: "#111827",
        },
        card: {
          DEFAULT: "#FFFFFF",
          foreground: "#111827",
        },
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px",
        'card': '20px',
      },
      spacing: {
        "md": "24px",
        "gutter": "24px",
        "xl": "80px",
        "xs": "4px",
        "margin-mobile": "16px",
        "sm": "12px",
        "lg": "48px",
        "base": "8px",
        "margin-desktop": "64px",
        'section-desktop': '96px',
        'section-tablet': '72px',
        'section-mobile': '56px',
      },
      fontFamily: {
        "headline-lg": ["Geist"],
        "label-md": ["Geist"],
        "body-lg": ["Geist"],
        "code-sm": ["JetBrains Mono"],
        "headline-md": ["Geist"],
        "body-md": ["Geist"],
        "body-sm": ["Geist"],
        "display-lg": ["Geist"],
        sans: ["Geist", "Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "code-sm": ["13px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        'display-mobile': ['36px', { lineHeight: '1.2', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-tablet': ['44px', { lineHeight: '1.2', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-desktop': ['56px', { lineHeight: '1.2', letterSpacing: '-0.04em', fontWeight: '700' }],
      },
      maxWidth: {
        'content': '720px',
        'container-main': '1280px',
      },
      boxShadow: {
        'card': '0 2px 10px rgba(0, 0, 0, 0.05)',
        'card-hover': '0 8px 30px rgba(0, 0, 0, 0.1)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "float": "float 6s ease-in-out infinite",
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries")
  ],
}
export default config;
